# Generated by Django 5.2.1 on 2025-06-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_certification"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="desired_job_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="languages",
            field=models.CharField(
                blank=True, help_text="Comma-separated languages", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="preferred_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_summary",
            field=models.TextField(blank=True),
        ),
    ]
